import{a as p,S as g,i as u}from"./assets/vendor-BBPOLzfb.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();p.defaults.baseURL="https://pixabay.com/api/";const f="49397541-1939e7fe1ba522fc58da934d1",y=async o=>{try{return(await p.get("",{params:{key:f,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,color:"black",per_page:9}})).data.hits.map(({id:i,webformatURL:s,largeImageURL:e,tags:r,likes:a,views:n,comments:l,downloads:c})=>({id:i,webformatURL:s,largeImageURL:e,tags:r,likes:a,views:n,comments:l,downloads:c}))}catch(t){return console.error("Error fetching photos:",t),[]}},b=o=>{const t=document.querySelector(".gallery");o.length===0&&(t.innerHTML="");const i=o.map(({webformatURL:e,largeImageURL:r,tags:a,likes:n,views:l,comments:c,downloads:h})=>`
        <li class='gallery-item'>
          <a class='gallery-link' href='${r}'>
            <img class='gallery-image' src='${e}' alt='${a}'>
          </a>
          <ul class='image-info'>
            <li><h4>Likes</h4><p>${n}</p></li>
            <li><h4>Views</h4><p>${l}</p></li>
            <li><h4>Comments</h4><p>${c}</p></li>
            <li><h4>Downloads</h4><p>${h}</p></li>
          </ul>
        </li>`).join("");t.insertAdjacentHTML("beforeend",i),new g(".gallery a",{close:!0,animationSpeed:250,enableKeyboard:!0,showCounter:!0,docClose:!0,captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250}).refresh()},d=o=>{const t=document.querySelector(".loader");o==="add"?t.classList.remove("is-hidden"):o==="remove"&&t.classList.add("is-hidden")},m=()=>{const o=document.querySelector(".gallery");o.innerHTML=""},L=document.querySelector(".form");document.querySelector(".gallery");const S=o=>{o.preventDefault();const t=o.target.elements["search-text"].value.trim();if(t===""){u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",maxWidth:"432px"}),m();return}m(),d("add"),y(t).then(i=>{if(i.length===0)return u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",maxWidth:"432px"});setTimeout(()=>{b(i)},1e3)}).catch(i=>{console.log(i),u.error({message:"Something went wrong! Please try again later.",position:"topRight",maxWidth:"432px"})}).finally(()=>{setTimeout(()=>{d("remove")},1e3)})};L.addEventListener("submit",S);
//# sourceMappingURL=index.js.map
