import{a as n,S as g,i as l}from"./assets/vendor-BBPOLzfb.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();n.defaults.baseURL="https://api.example.com";n.defaults.params={color:"black",orientation:"landscape",per_page:9};const f=r=>n.get(`https://pixabay.com/api/?key=49397541-1939e7fe1ba522fc58da934d1&q=${r}&image_type=photo`).then(t=>t.data.hits),y=r=>{const t=document.querySelector(".gallery");r.length===0&&(t.innerHTML="");const i=r.map(({webformatURL:e,largeImageURL:o,tags:a,likes:d,views:m,comments:p,downloads:h})=>`
        <li class='gallery-item'>
          <a class='gallery-link' href='${o}'>
            <img class='gallery-image' src='${e}' alt='${a}'>
          </a>
          <ul class='image-info'>
            <li><h4>Likes</h4><p>${d}</p></li>
            <li><h4>Views</h4><p>${m}</p></li>
            <li><h4>Comments</h4><p>${p}</p></li>
            <li><h4>Downloads</h4><p>${h}</p></li>
          </ul>
        </li>`).join("");t.insertAdjacentHTML("beforeend",i),new g(".gallery a",{close:!0,animationSpeed:250,enableKeyboard:!0,showCounter:!0,docClose:!0,captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250}).refresh()},c=r=>{const t=document.querySelector(".loader");r==="add"?t.classList.remove("is-hidden"):r==="remove"&&t.classList.add("is-hidden")},u=()=>{const r=document.querySelector(".gallery");r.innerHTML=""},b=document.querySelector(".form");document.querySelector(".gallery");const L=r=>{r.preventDefault();const t=r.target.elements["search-text"].value.trim();if(t===""){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",maxWidth:"432px"}),u();return}u(),c("add"),f(t).then(i=>{if(i.length===0)return l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",maxWidth:"432px"});setTimeout(()=>{y(i)},1e3)}).catch(i=>{console.log(i),l.error({message:"Something went wrong! Please try again later.",position:"topRight",maxWidth:"432px"})}).finally(()=>{setTimeout(()=>{c("remove")},1e3)})};b.addEventListener("submit",L);
//# sourceMappingURL=index.js.map
